package com.example.androidestudy.feature.todoapp.presentation.util

import com.example.androidestudy.feature.todoapp.presentation.home.component.Priority
import com.example.androidestudy.feature.todoapp.presentation.home.component.todo.TodoItemState

val fakeTodoList = listOf(
    TodoItemState(
        1,
        "a",
        "a",
        Priority.High,
        "2023/01/01"
    ),TodoItemState(
        2,
        "b",
        "b",
        Priority.High,
        "2023/01/01"
    ),TodoItemState(
        3,
        "c",
        "c",
        Priority.High,
        "2023/01/01"
    ),TodoItemState(
        4,
        "d",
        "",
        Priority.High,
        "2023/01/01"
    ),TodoItemState(
        5,
        "e",
        "e",
        Priority.High,
        "2023/01/01"
    ),TodoItemState(
        6,
        "f",
        "f",
        Priority.Medium,
        "2023/01/01"
    ),TodoItemState(
        7,
        "g",
        "g",
        Priority.Medium,
        "2023/01/01"
    ),TodoItemState(
        8,
        "h",
        "h",
        Priority.Medium,
        "2023/01/01"
    ),TodoItemState(
        9,
        "i",
        "i",
        Priority.Medium,
        "2023/01/01"
    ),TodoItemState(
        10,
        "j",
        "j",
        Priority.Medium,
        "2023/01/01"
    ),TodoItemState(
        11,
        "k",
        "k",
        Priority.Low,
        "2023/01/01"
    ),TodoItemState(
        12,
        "l",
        "l",
        Priority.Low,
        "2023/01/01"
    ),TodoItemState(
        13,
        "m",
        "m",
        Priority.Low,
        "2023/01/01"
    ),TodoItemState(
        14,
        "n",
        "n",
        Priority.Low,
        "2023/01/01"
    ),TodoItemState(
        15,
        "o",
        "o",
        Priority.Low,
        "2023/01/01"
    ),
)